=== maybuzani/Liga-xm-xml/xsd/resultados.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="resultados_liga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="partido" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo_local" type="xs:string"/>
                            <xs:element name="goles_local" type="xs:integer"/>
                            <xs:element name="equipo_visitante" type="xs:string"/>
                            <xs:element name="goles_visitante" type="xs:integer"/>
                            <xs:element name="estadio" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== maybuzani/Liga-xm-xml/xml/resultados.xml
<?xml version="1.0" encoding="UTF-8"?>
<resultados_liga xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../xsd/resultados.xsd">
    <partido>
        <equipo_local>Guadalajara</equipo_local>
        <goles_local>2</goles_local>
        <equipo_visitante>América</equipo_visitante>
        <goles_visitante>1</goles_visitante>
        <estadio>Estadio Akron</estadio>
    </partido>
    <partido>
        <equipo_local>Tigres</equipo_local>
        <goles_local>1</goles_local>
        <equipo_visitante>Monterrey</equipo_visitante>
        <goles_visitante>1</goles_visitante>
        <estadio>Estadio Universitario</estadio>
    </partido>
</resultados_liga>
